[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/amgp-upm/dl_course_chile/blob/main/1_Introduccion.ipynb)

In [1]:
import torch
import numpy as np
import matplotlib.pyplot as plt

### Matrices y Tensores

In [2]:
x = np.ones([2, 3], dtype=np.double)
x, type(x)

(array([[1., 1., 1.],
        [1., 1., 1.]]), numpy.ndarray)

In [3]:
x = torch.ones(2, 3)
x, type(x)

(tensor([[1., 1., 1.],
         [1., 1., 1.]]), torch.Tensor)

In [4]:
# covertir un numpy.ndarray en torch.Tensor
x = torch.Tensor(np.ones([2, 3]))
x, type(x)

(tensor([[1., 1., 1.],
         [1., 1., 1.]]), torch.Tensor)

In [5]:
# covertir un torch.Tensor en numpy.ndarray
x = torch.ones(2, 3).numpy()
x, type(x)

(array([[1., 1., 1.],
        [1., 1., 1.]], dtype=float32), numpy.ndarray)

### Tipos de datos y equivalencias entre numpy y torch

| NumPy Array Type | Torch Tensor Type | 
| --- | --- | 
| int64 | LongTensor | 
| int32 | IntegerTensor | 
| uint8 | ByteTensor | 
| float64 | DoubleTensor | 
| float32 | FloatTensor | 
| double | DoubleTensor | 

### Importacia de establecer una semilla
Como se trabaja con números pseudo-aleatorios es importante establecer una semilla para garantizar la reproducibilidad de los resultados.

In [6]:
# resultados de la generación de números "aleatorios" en numpy
print(f'Primera ejecución: {np.random.rand(5)}')
print(f'Segunda ejecución: {np.random.rand(5)}')

Primera ejecución: [0.55942596 0.64535207 0.97417797 0.72485776 0.55252142]
Segunda ejecución: [0.89233855 0.42224173 0.75861541 0.85263623 0.94843956]


In [7]:
# Ahora estableciendo una semilla antes de cada ejecución
np.random.seed(23)
print(f'Primera ejecución: {np.random.rand(5)}')
np.random.seed(23)
print(f'Segunda ejecución: {np.random.rand(5)}')

Primera ejecución: [0.51729788 0.9469626  0.76545976 0.28239584 0.22104536]
Segunda ejecución: [0.51729788 0.9469626  0.76545976 0.28239584 0.22104536]


In [8]:
# Ahora con PyTorch
print(f'Primera ejecución: {torch.rand(5)}')
print(f'Segunda ejecución: {torch.rand(5)}')

Primera ejecución: tensor([0.0889, 0.5281, 0.2305, 0.9543, 0.7977])
Segunda ejecución: tensor([0.3030, 0.4848, 0.2452, 0.2176, 0.5230])


In [9]:
torch.manual_seed(23)
print(f'Primera ejecución: {torch.rand(5)}')
torch.manual_seed(23)
print(f'Segunda ejecución: {torch.rand(5)}')

Primera ejecución: tensor([0.4283, 0.2889, 0.4224, 0.3571, 0.9577])
Segunda ejecución: tensor([0.4283, 0.2889, 0.4224, 0.3571, 0.9577])


### Operaciones con tensores

In [10]:
a = torch.ones(3, 2)
b = torch.ones(3, 2) * 2
print(a)
print(b)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])


Obtener tamaño

In [11]:
print(a.size(), b.size())

torch.Size([3, 2]) torch.Size([3, 2])


Cambiar el tamaño 

In [12]:
print(a.view(6), a.view(6).size())
print(a.view(2,3,1), a.view(2,3,1).size())

tensor([1., 1., 1., 1., 1., 1.]) torch.Size([6])
tensor([[[1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.]]]) torch.Size([2, 3, 1])


Suma y resta elemento a elemento

In [13]:
c = a + b
print(c)
c = torch.add(a, b)
print(c)

tensor([[3., 3.],
        [3., 3.],
        [3., 3.]])
tensor([[3., 3.],
        [3., 3.],
        [3., 3.]])


In [14]:
c = a - b
print(c)
c = torch.subtract(a, b)
print(c)

tensor([[-1., -1.],
        [-1., -1.],
        [-1., -1.]])
tensor([[-1., -1.],
        [-1., -1.],
        [-1., -1.]])


Multiplicación y división elemento a elemento

In [15]:
c = a * b
print(c)
c = torch.mul(a, b)
print(c)

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])
tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])


In [16]:
c = a / b
print(c)
c = torch.div(a, b)
print(c)

tensor([[0.5000, 0.5000],
        [0.5000, 0.5000],
        [0.5000, 0.5000]])
tensor([[0.5000, 0.5000],
        [0.5000, 0.5000],
        [0.5000, 0.5000]])


Valor medio. 


In [17]:
a = torch.ones(2, 3)

# Nota: Se puede calcular a partir de todos los valores 

print(torch.mean(a)) 
print(a.mean())

# Nota: Se puede definir la dimensión a reducir.

x = a.mean(dim=0) 
print(x, x.size())

x = a.mean(dim=1) 
print(x, x.size())

tensor(1.)
tensor(1.)
tensor([1., 1., 1.]) torch.Size([3])
tensor([1., 1.]) torch.Size([2])


### Gradiente

Ecuación a derivar $y_i=4(x_i+2)^2$

Derivada $\frac{dy_i}{dx_i}=8x_i+16$

In [18]:
x = torch.Tensor((1, 4, 7)).requires_grad_()
x

tensor([1., 4., 7.], requires_grad=True)

In [19]:
y = 4 * (x + 2) ** 2

print(f'Funcion valuada: {y}')

Funcion valuada: tensor([ 36., 144., 324.], grad_fn=<MulBackward0>)


Derivada obtenida por PyTorch mediante la función Backward. Ésta solo debe invocarse sobre un escalar (es decir, un tensor de 1 elemento). Para ello se calculará el valor medio.


In [20]:
o = torch.mean(y)
print(o)

tensor(168., grad_fn=<MeanBackward0>)


Esto cambiaría la ecuación a derivar
Ecuación a derivar $y_i=4(x_i+2)^2$

output = $\frac{1}{3}\sum_i=4(x_i+2)^2$

$\frac{\partial o}{\partial x_i}=\frac{1}{3}(8x_i+16)$

In [21]:
o.backward()
print(x.grad)

tensor([ 8., 16., 24.])
